server:
  port: 9999
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 100MB
      max-request-size: 10000MB

# Mybatis-Plus Config http://mp.baomidou.com/#/spring-boot
mybatis-plus:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  typeAliasesPackage: com.baizhi.cmfz_mzw.enetity

pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

